#!/bin/bash
# bashfiles - Manage CloudFiles via the command-line

BF_VERSION=0.1
BF_PROG=`basename $0`
BF_DEFAULT_CONTENT_TYPE=application/octet-stream
BF_CONFIG_DIR=~/.$BF_PROG
BF_ENDPOINTS_DIR=$BF_CONFIG_DIR/endpoints
BF_CHECKSUM_PROGRESS_MIN_SIZE=10485760 # 10 MB

OPT_CONTENT_TYPE=
OPT_ENDPOINT=default
OPT_FORCE=0
OPT_INPUT=
OPT_OUTPUT=
OPT_QUIET=0

CONST_ZERO_MD5=d41d8cd98f00b204e9800998ecf8427e


#############################################################################
#                                                                           #
#                               Bashfiles                                   #
#                                                                           #
#############################################################################


function bf_help() {
    cat <<'EOF'
SYNOPSIS

    bashfiles [options] [commands] [container] [object-names]

DESCRIPTION

    `bashfiles` is a utility for working with Rackspace CloudFiles via the
    command-line. `bashfiles` has minimal dependencies, requiring only bash,
    curl, and a few other POSIX utilities.

    You can pass settings to `bashfiles` via environment variables or by
    defining a configuration file located at `~/.bashfiles`.

OPTIONS

    -b      Print bash completion script
    -e      Use endpoint
    -f      Force
    -h      Print help
    -i      Input filename (- for stdin)
    -o      Output filename (- for stdout)
    -q      Quiet mode
    -t      Set Content-Type for upload
    -v      Print version

COMMANDS

    cp      Server-side object copy

            -f Overwrite destination object if exists

    endpoint Manage endpoints

                add     Add endpoint
                ls      List all endpoints
                rm      Remove endpoint
                show    Show endpoint settings

    get     Download file (-f overwrites existing file, if present)

            -f Overwrite local file if exists
            -o Output to different filename, - for stdout

    ls      List all containers or contents of a specific container

    mkdir   Create a container

    mv      Server-side object move

            -f Overwrite destination object if exists

    put     Upload file

            -f Overwrite remote object if exists
            -i Input from different filename, - for stdin
            -t Set Content-Type for upload

    rm      Remove object

    rmdir   Remove container

            -f Clear container before removing it

    stat    Account, container, or object information

SETTINGS

    CF_USER         CloudFiles username
    CF_API_KEY      CloudFiles API Key
    CF_AUTH_URL     CloudFiles authentication URL
    CF_SERVICENET   Use Rackspace's ServiceNET network
    CF_INSECURE     Disable SSL certificate verification
    CF_SEGMENT_SIZE Size in bytes of large-file segments (5GB default)

FILES

    ~/.bashfiles/endpoints/*

AUTHORS

    Rick Harris

BUGS

    Report to https://github.com/rconradharris/bashfiles
EOF
    exit 0
}


function bf_bash_completion() {
    cat <<'EOF'
# Search array1 for any element in array2. Stop on first match. -1 on not
# found.
function _bf_match() {
    declare -a array1=("${!1}")
    declare -a array2=("${!2}")

    local i=0
    while [[ $i -lt ${#array1[@]} ]]; do
        local j=0
        while [[ $j -lt ${#array2[@]} ]]; do
            if [[ ${array1[i]} == ${array2[j]} ]]; then
                echo $i
                return
            fi
            let j++
        done
        let i++
    done

    echo '-1'
}


function _bf_completer() {
    COMPREPLY=()

    local OPTIONS=(-b -e -f -h -i -o -q -t -v)
    local COMMANDS=(cp endpoint get ls mkdir mv put rm rmdir stat)
    local ENDPOINT_COMMANDS=(add ls rm show)

    local cmd=
    local container_idx=
    local container_fname=
    local object_fname=
    local opts=

    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    local endpoint=default

    local ENDPOINT_OPTIONS=(-e)
    local endpoint_idx=`_bf_match COMP_WORDS[@] ENDPOINT_OPTIONS[@]`
    if [[ $endpoint_idx -ne -1 ]]; then
        endpoint=${COMP_WORDS[endpoint_idx+1]}
    fi

    local BF_CONFIG_DIR=~/.bashfiles
    local BF_ENDPOINTS_DIR=$BF_CONFIG_DIR/endpoints
    local BF_COMPLETION_DIR=$BF_CONFIG_DIR/completion/$endpoint

    local cmd_idx=`_bf_match COMP_WORDS[@] COMMANDS[@]`
    if [[ $cmd_idx -ne -1 ]]; then
        cmd=${COMP_WORDS[cmd_idx]}
        container_idx=`expr $cmd_idx + 1`
        container_fname=$BF_COMPLETION_DIR/container-names
        object_fname=$BF_COMPLETION_DIR/${COMP_WORDS[container_idx]}-object-names
    fi

    if [[ $prev == '-e' && -d $BF_ENDPOINTS_DIR ]]; then
        opts=`ls $BF_ENDPOINTS_DIR | tr '\n' ' '`
    elif [[ $prev == '-i' ]]; then
        COMPREPLY=($(compgen -f $cur))
        return
    elif [[ $cmd_idx -eq -1 && ${cur:0:1} == '-' ]]; then
        # Option (no command yet, starts with -)
        opts="${OPTIONS[@]}"
    elif [[ $cmd_idx -eq -1 ]]; then
        # Command (no command yet, anything else)
        opts="${COMMANDS[@]}"
    elif [[ $cmd == 'endpoint' ]]; then
        if [[ $prev == 'rm' || $prev == 'show' ]]; then
            if [[ -d $BF_ENDPOINTS_DIR ]]; then
                opts=`ls $BF_ENDPOINTS_DIR | tr '\n' ' '`
            fi
        else
            opts="${ENDPOINT_COMMANDS[@]}"
        fi
    elif [[ $COMP_CWORD -eq $container_idx && -r $container_fname ]]; then
        # Containers (after command)
        opts=`cat $container_fname | tr '\n' ' '`
    elif [[ $cmd == 'put' ]]; then
        # put completes to filenames not object-names
        COMPREPLY=($(compgen -f $cur))
        return
    elif [[ $cmd == 'ls' ]]; then
        # ls doesn't complete to object-names
        return
    elif [[ -r $object_fname ]]; then
        # Everything else completes to a list of object-names
        opts=`cat $object_fname | tr '\n' ' '`
    fi

    COMPREPLY=($(compgen -W "$opts" -- $cur))
}


complete -F _bf_completer bashfiles
EOF
    exit 0
}


function bf_log() {
    if [[ $OPT_QUIET -eq 0 ]]; then
        echo "$@" >&2
    fi
}


function bf_warn() {
    echo "warning: $@" >&2
}


function bf_die() {
    echo "error: $@" >&2
    exit 1
}


function bf_version() {
    echo $BF_VERSION
    exit 0
}


function bf_usage() {
    echo "usage: $BF_PROG [-befhqstv] $@" >&2
    exit 1
}


function bf_general_usage() {
    bf_usage "<cp|endpoint|get|ls|mkdir|mv|put|rm|rmdir|stat> [container]" \
             "[object-name]"
}


function bf_ask() {
    local question=$1

    read -p "$question "
    echo $REPLY
}


function bf_ask_required() {
    # NOTE: this function should not be spawned in a subshell b/c it has the
    # side-effect of exiting on an empty reply. This is why we have to return
    # the result by `eval` instead of `echo`ing from a subshell
    local var=$1
    local question=$2
    local reply=`bf_ask "$question"`
    if [[ -z $reply ]]; then
        echo 'Aborted' >&2
        exit 1
    fi
    eval $var="'$reply'"
}


function bf_ask_with_default() {
    local default=$1
    local question=$2

    local reply=`bf_ask "$question"`

    if [[ -z $reply ]]; then
        reply=$default
    fi

    echo "$reply"
}


function bf_ask_yes_no() {
    local default=$1
    local question=$2
    local ret=
    local hint=

    if [[ $default == 'Y' || $default == 'y' ]]; then
        hint="[Y/n]"
    else
        hint="[y/N]"
    fi

    local reply=`bf_ask_with_default "$default" "$question $hint?"`
    if [[ $reply == 'Y' || $reply == 'y' ]]; then
        ret=1
    else
        ret=0
    fi

    echo $ret
}


function bf_md5() {
    local filename=$1

    local size=`bf_size $filename`
    local cmd=

    # Provide checksum progress using `pv` if `pv` is present and we're above
    # the minimum size cut-off
    if [[ -n `which pv` && $size -ge BF_CHECKSUM_PROGRESS_MIN_SIZE ]]; then
        cmd="pv $filename | "
    else
        cmd="cat $filename | "
    fi

    if [[ `uname` == "Darwin" ]]; then
        cmd="${cmd}md5 -q"
    else
        cmd="${cmd}md5sum | cut -d' ' -f1"
    fi

    echo $(eval $cmd)
}


function bf_urlencode() {
    # http://gimi.name/snippets/urlencode-and-urldecode-for-bash-scripting-using-sed/
    echo "$1" | sed -e 's/%/%25/g;s/ /%20/g;s/ /%09/g;s/!/%21/g;s/"/%22/g;' \
                    -e 's/#/%23/g;s/\$/%24/g;s/\&/%26/g;s/'\''/%27/g;'\
                    -e 's/(/%28/g;s/)/%29/g;s/\*/%2a/g;s/+/%2b/g;'\
                    -e 's/,/%2c/g; s/-/%2d/g; s/\./%2e/g; s/:/%3a/g;'\
                    -e 's/;/%3b/g; s//%3e/g; s/?/%3f/g; s/@/%40/g;'\
                    -e 's/\[/%5b/g; s/\\/%5c/g; s/\]/%5d/g; s/\^/%5e/g;'\
                    -e 's/_/%5f/g; s/`/%60/g; s/{/%7b/g; s/|/%7c/g;'\
                    -e 's/}/%7d/g; s/~/%7e/g; s/      /%09/g;'
}


function bf_mktemp() {
    if [[ `uname` == "Darwin" ]]; then
        echo `mktemp -t $BF_PROG`
    else
        echo `mktemp -t $BF_PROG.XXXXXXXXX`
    fi
}


function bf_size() {
    local filename=$1

    if stat -c 2>&1 | grep -q illegal; then
        # Mac OS X
        echo `stat -f%z ${filename}`
    else
        # Linux
        echo `stat -c%s ${filename}`
    fi
}


function bf_compute_num_blocks() {
    local total_size=$1
    local block_size=$2

    local nblocks=$((total_size / $block_size))

    if [[ $((total_size % $block_size)) -gt 0 ]]; then
        let nblocks++
    fi

    echo $nblocks
}


function bf_autodetect_filetype() {
    local filename=$1
    echo `file --brief --mime $filename`
}


function bf_save_endpoint_config() {
    mkdir -p `dirname $BF_ENDPOINT_CONFIG`

    if [[ -e $BF_ENDPOINT_CONFIG ]]; then
        bf_warn "Cannot save, endpoint config '$BF_ENDPOINT_CONFIG'" \
                "already exists"
        return 1
    fi

    touch $BF_ENDPOINT_CONFIG

    cf_save_endpoint_config
}


function bf_load_endpoint_config_file() {
    if [[ -r $BF_ENDPOINT_CONFIG ]]; then
        source $BF_ENDPOINT_CONFIG
    fi
}


function bf_load_endpoint_config_interactive() {
    cf_load_endpoint_config_interactive

    if [[ $? -ne 0 ]]; then
        return
    fi

    if [[ `bf_ask_yes_no n 'Save settings'` -eq 1 ]]; then
        bf_save_endpoint_config
    fi
}


function bf_load_endpoint_config() {
    BF_ENDPOINT_CONFIG=$BF_ENDPOINTS_DIR/$OPT_ENDPOINT
    BF_COMPLETION_DIR=$BF_CONFIG_DIR/completion/$OPT_ENDPOINT

    bf_load_endpoint_config_file
    bf_load_endpoint_config_interactive
}


function bf_init() {
    bf_load_endpoint_config
}


#############################################################################
#                                                                           #
#                               Commands                                    #
#                                                                           #
#############################################################################


function cmd_cp() {
    local src_container=$1
    local src_obj_name=$2
    local dst_container=$3
    local dst_obj_name=$4

    if [[ -z $src_container || -z $src_obj_name
                            || -z $dst_container \
                            || -z $dst_obj_name ]]; then
        bf_usage 'cp <src-container> <src-object-name>' \
                 ' <dst-container> <dst-object-name>'
    fi

    bf_init

    if [[ $OPT_FORCE -ne 1 ]]; then
        cf_assert_objects_missing $dst_container $dst_obj_name
    fi

    cf_cp $src_container $src_obj_name $dst_container $dst_obj_name
}


function cmd_endpoint_add() {
    local endpoint=$1

    if [[ -z $endpoint ]]; then
        bf_usage 'endpoint add <endpoint>'
    fi

    if [[ -e $BF_ENDPOINTS_DIR/$endpoint ]]; then
        bf_die "Endpoint '$endpoint' already exists"
    fi

    OPT_ENDPOINT=$endpoint
    bf_load_endpoint_config
}


function cmd_endpoint_ls() {
    # NOTE: cat is needed here so that we get one entry per line. This works
    # by diguising from `ls` the fact that we're actually a tty
    ls $BF_ENDPOINTS_DIR | cat
}


function cmd_endpoint_rm() {
    local endpoint=$1

    if [[ -z $endpoint ]]; then
        bf_usage 'endpoint rm <endpoint>'
    fi

    rm $BF_ENDPOINTS_DIR/$endpoint

    local completion_dir=$BF_CONFIG_DIR/completion/$endpoint
    if [[ -d $completion_dir ]]; then
        rm $completion_dir/*
        rmdir $completion_dir
    fi
}


function cmd_endpoint_show() {
    local endpoint=$1

    if [[ -z $endpoint ]]; then
        bf_usage 'endpoint show <endpoint>'
    fi

    cat $BF_ENDPOINTS_DIR/$endpoint
}


function cmd_endpoint() {
    local subcommand=$1
    shift

    case $subcommand in
        add)    cmd_endpoint_add    $@;;
        ls)     cmd_endpoint_ls     $@;;
        rm)     cmd_endpoint_rm     $@;;
        show)   cmd_endpoint_show   $@;;
        *)      bf_usage 'endpoint [add|ls|rm|show]';;
    esac
}


function cmd_get() {
    local container=$1
    shift
    local obj_names=$@

    if [[ -z $container || -z $obj_names ]]; then
        bf_usage 'get <container> <object-names>'
    fi

    if [[ -n $OPT_OUTPUT && $# -gt 1 ]]; then
        bf_die "-o can only be used to download a single file"
    fi

    bf_init

    cf_get $container $obj_names
}


function cmd_ls() {
    local container=$1
    local tmp_file=`bf_mktemp`

    bf_init

    cf_ls "$container" $tmp_file

    cat $tmp_file

    # Refresh bash-completion cache
    mkdir -p $BF_COMPLETION_DIR
    if [[ -z $container ]]; then
        mv $tmp_file $BF_COMPLETION_DIR/container-names
    else
        mv $tmp_file $BF_COMPLETION_DIR/$container-object-names
    fi
}


function cmd_mkdir() {
    local containers=$@

    if [[ -z $containers ]]; then
        bf_usage 'mkdir <containers>'
    fi

    bf_init

    cf_mkdir $containers
}


function cmd_mv() {
    local src_container=$1
    local src_obj_name=$2
    local dst_container=$3
    local dst_obj_name=$4

    if [[ -z $src_container || -z $src_obj_name
                            || -z $dst_container \
                            || -z $dst_obj_name ]]; then
        bf_usage 'mv <src-container> <src-object-name>' \
                 ' <dst-container> <dst-object-name>'
    fi

    bf_init

    if [[ $OPT_FORCE -ne 1 ]]; then
        cf_assert_objects_missing $dst_container $dst_obj_name
    fi

    cf_mv $src_container $src_obj_name $dst_container $dst_obj_name
}


function cmd_put() {
    local container=$1
    shift
    local obj_names=$@

    if [[ -z $container || -z $obj_names ]]; then
        bf_usage 'put <container> <object-names>'
    fi

    if [[ -n $OPT_INPUT && $# -gt 1 ]]; then
        bf_die "-i can only be used to upload a single file"
    fi

    bf_init

    if [[ $OPT_FORCE -ne 1 ]]; then
        cf_assert_objects_missing $container $obj_names
    fi

    cf_put $container $obj_names
}


function cmd_rm() {
    local container=$1
    shift
    local obj_names=$@

    if [[ -z $container || -z $obj_names ]]; then
        bf_usage 'rm <container> <object-names>'
    fi

    bf_init

    cf_rm $container $obj_names
}


function cmd_rmdir() {
    local containers=$@

    if [[ -z $containers ]]; then
        bf_usage 'rmdir <containers>'
    fi

    bf_init

    cf_rmdir $containers
}


function cmd_stat() {
    local container=$1
    shift
    local obj_names=$@

    # NOTE: No arg checking because we can accept any number of arguments:
    #
    #    0 - Account statistics
    #    1 - Container statistics
    # >= 2 - Object statistics

    bf_init

    cf_stat $container "$obj_names"
}


#############################################################################
#                                                                           #
#                               CloudFiles                                  #
#                                                                           #
#############################################################################


CF_DEFAULT_AUTH_URL_US=https://auth.api.rackspacecloud.com/v1.0
CF_DEFAULT_AUTH_URL_UK=https://lon.auth.api.rackspacecloud.com/v1.0
CF_DEFAULT_SEGMENT_SIZE=5368709120
CF_DD_BLOCK_SIZE=1024


function cf_check_ok() {
    local code=$1

    if [[ $code -lt 200 || $code -gt 299 ]]; then
        bf_die "Invalid response code: $code"
    fi
}


function cf_curl() {
    local url=$1
    shift

    if [[ $CF_INSECURE -eq 1 ]]; then
        local curl_opts=--insecure
    else
        local curl_opts=
    fi

    curl $curl_opts --fail "$@" "$url"
}


function cf_handle_snet() {
    if [[ $CF_SERVICENET -eq 1 ]]; then
        CF_STORAGE_URL=${CF_STORAGE_URL/https:\/\//https://snet-}
        CF_STORAGE_URL=${CF_STORAGE_URL/http:\/\//http://snet-}
    fi
}


function cf_auth() {
    if [[ -n $CF_AUTH_TOKEN ]]; then
        return
    fi

    local tmp_headers=`bf_mktemp`

    if [[ -z $CF_AUTH_URL ]]; then
        CF_AUTH_URL=$CF_DEFAULT_AUTH_URL_US
    fi

    local code=$(
        cf_curl ${CF_AUTH_URL} --silent --write-out '%{http_code}' \
                               --dump-header $tmp_headers \
                               --header "X-Auth-Key: $CF_API_KEY" \
                               --header "X-Auth-User: $CF_USER")

    cf_check_ok $code

    CF_AUTH_TOKEN=$(cat $tmp_headers | grep ^X-Auth-Token \
                                     | sed 's/.*: //' \
                                     | tr -d "\r\n")

    CF_STORAGE_URL=$(cat $tmp_headers | grep ^X-Storage-Url \
                                      | sed 's/.*: //' \
                                      | tr -d "\r\n")

    if [[ -z $CF_AUTH_TOKEN || -z $CF_STORAGE_URL ]]; then
        bf_die "Unable to authenticate to CloudFiles"
    fi

    cf_handle_snet
    rm $tmp_headers
}


function cf_request() {
    local url=$1
    shift

    cf_auth
    cf_curl "$CF_STORAGE_URL/$url" --header "X-Auth-Token: $CF_AUTH_TOKEN" \
            "$@"
}


function cf_request_return_code() {
    local code=`cf_request "$@" --write-out '%{http_code}'`
    echo $code
}


function cf_request_check_ok() {
    local code=`cf_request_return_code "$@"`
    cf_check_ok $code
}


function cf_request_smart_silent() {
    if [[ $OPT_QUIET -eq 1 ]]; then
        local opt_silent=--silent
    else
        local opt_silent=
    fi

    cf_request_check_ok "$@" $opt_silent
}


function cf_request_put_object() {
    local container=$1
    local obj_name=$2
    local content_type=$3
    shift
    shift
    shift

    container_name=`bf_urlencode $container_name`
    obj_name=`bf_urlencode $obj_name`

    cf_request_smart_silent $container/$obj_name --request PUT \
                            --header "Content-Type: $content_type" "$@" 
}


function cf_cp() {
    local src_container=$1
    local src_obj_name=$2
    local dst_container=$3
    local dst_obj_name=$4

    cf_request_check_ok $src_container/$src_obj_name --silent --request COPY \
                        --header "Destination: /$dst_container/$dst_obj_name"
}


function cf_ls() {
    local container=$1
    local tmp_file=$2

    cf_request_check_ok "$container" --silent --output $tmp_file
}


function cf_get() {
    local container=$1
    shift
    local obj_names=$@

    local obj_name=
    for obj_name in $obj_names; do
        if [[ -n $OPT_OUTPUT ]]; then
            local filename=$OPT_OUTPUT
        else
            local filename=`basename $obj_name`
        fi

        if [[ $filename == - ]]; then
            container_name=`bf_urlencode $container_name`
            obj_name=`bf_urlencode $obj_name`
            cf_request $container/$obj_name --silent
            continue
        elif [[ $OPT_FORCE -ne 1 ]]; then
            if [[ -e $filename ]]; then
                bf_die "File '$filename' already exists, use -f to overwrite"
            fi
        fi

        local output=.$filename.download
        local tmp_headers=`bf_mktemp`

        cf_request_smart_silent $container/$obj_name \
                                --dump-header $tmp_headers \
                                --output $output


        local etag=$(cat $tmp_headers | grep --ignore-case ^Etag \
                                      | sed 's/.*: //' \
                                      | tr -d "\r\n" \
                                      | tr -d '"')

        if [[ -z `grep --ignore-case X-Object-Manifest $tmp_headers` ]]; then
            local dlo=0
        else
            # NOTE: Dynamic Large Objects won't have an ETag that matches
            local dlo=1
        fi

        rm $tmp_headers

        if [[ $output == - ]]; then
            true
        elif [[ $etag == $CONST_ZERO_MD5 ]]; then
            # NOTE: If it's a 0-byte file, curl will not create the output
            # file, so we have to do that ourselves
            touch $filename
            bf_warn "Zero-byte file created"
        elif [[ $dlo -eq 1 || $etag == `bf_md5 $output` ]]; then
            mv $output $filename
        else
            rm $output
            bf_die "Failed checksum validation."
        fi
    done
}


function cf_mkdir() {
    local containers=$@
    local container=

    for container in $containers; do
        cf_request_check_ok $container --silent --output /dev/null \
                            --request PUT --upload-file /dev/null
    done
}


function cf_mv() {
    local src_container=$1
    local src_obj_name=$2
    local dst_container=$3
    local dst_obj_name=$4

    cf_cp $src_container $src_obj_name $dst_container $dst_obj_name
    cf_rm $src_container $src_obj_name
}


function cf_put_file_small() {
    local container=$1
    local filename=$2
    local obj_name=$3
    local content_type=$4
    local size=$5
    local segment_size=$6

    bf_log "Computing MD5 checksum for '$filename'..."
    local etag=`bf_md5 $filename`

    bf_log "Uploading '$obj_name' to '$container'..."
    cf_request_put_object $container $obj_name "$content_type" \
                          --header "ETag: $etag" --upload-file $filename
}


function cf_put_file_large() {
    local container=$1
    local filename=$2
    local obj_name=$3
    local content_type=$4
    local size=$5
    local segment_size=$6

    local left=$size
    local segment_num=1
    local skip=0
    local length=
    local seg_name=
    local nblocks=

    local seg_container=${obj_name}_segments
    local obj_prefix="$obj_name/`date +%s`/$size"
    local total_segments=`bf_compute_num_blocks $size $segment_size`

    cf_mkdir ${seg_container}

    while [[ $left -gt 0 ]]; do
        bf_log "Uploading segment $segment_num/$total_segments"

        if [[ $left -ge $segment_size ]]; then
            length=$segment_size
        else
            length=$left
        fi

        seg_name="$obj_prefix/`printf '%08d' $segment_num`"
        nblocks=`bf_compute_num_blocks $length $CF_DD_BLOCK_SIZE`

        dd if=$filename bs=$CF_DD_BLOCK_SIZE count=$nblocks skip=$skip \
                        2> /dev/null | \
            cf_request_put_object $seg_container $seg_name "$content_type" \
                                  --upload-file -

        let left-=$length
        let skip+=$nblocks
        let segment_num++

        bf_log ""
    done

    bf_log "Uploading manifest for ${filename}"

    local manifest="$seg_container/$obj_prefix/"
    cf_request_put_object $container $obj_name "$content_type" \
                          --data-binary '' --output /dev/null \
                          --header "X-Object-Manifest: $manifest"
}


function cf_put_file() {
    local container=$1
    local obj_name=$2

    local filename=
    local segment_size=
    local content_type=
    local size=

    if [[ -n $OPT_INPUT ]]; then
        filename=$OPT_INPUT
    else
        filename=$obj_name
    fi

    if [[ ! -e $filename ]]; then
        bf_die "File '$filename' not found"
    fi

    if [[ -n $CF_SEGMENT_SIZE ]];  then
        segment_size=$CF_SEGMENT_SIZE
    else
        segment_size=$CF_DEFAULT_SEGMENT_SIZE
    fi

    if [[ -n $OPT_CONTENT_TYPE ]]; then
        content_type=$OPT_CONTENT_TYPE
    else
        content_type=`bf_autodetect_filetype $filename`
    fi

    size=`bf_size $filename`

    if [[ $size -gt $segment_size ]]; then
        cf_put_file_large $container $filename $obj_name \
                          "$content_type" $size $segment_size
    else
        cf_put_file_small $container $filename $obj_name \
                          "$content_type" $size $segment_size
    fi
}


function cf_put_stream() {
    local container=$1
    local obj_name=$2

    local content_type=

    if [[ -n $OPT_CONTENT_TYPE ]]; then
        content_type=$OPT_CONTENT_TYPE
    else
        content_type=$BF_DEFAULT_CONTENT_TYPE
    fi

    cf_request_put_object $container $obj_name "$content_type" --upload-file -
}


function cf_put() {
    local container=$1
    shift
    local obj_names=$@

    local obj_name=
    for obj_name in $obj_names; do
        if [[ $OPT_INPUT == - ]]; then
            cf_put_stream $container $obj_name
        else
            cf_put_file $container $obj_name
        fi
    done
}


function cf_rm() {
    local container=$1
    shift
    local obj_names=$@

    local obj_name=
    for obj_name in $obj_names; do
        cf_request_check_ok $container/$obj_name --silent --request DELETE
    done
}


function cf_clear_container() {
    local container=$1
    local tmp_file=`bf_mktemp`

    # TODO: handle pagination
    cf_ls $container $tmp_file
    obj_names=`cat $tmp_file`

    # NOTE: tr -d is needed for Mac OS X, since wc -w has leading spaces
    # in output
    local total_objects=`echo $obj_names | wc -w | tr -d ' '`
    local idx=1

    local obj_name=
    for obj_name in $obj_names; do
        bf_log "Deleting $idx/$total_objects: $obj_name"
        cf_rm $container $obj_name
        let idx++
    done

    rm $tmp_file
}


function cf_rmdir() {
    local containers=$@

    local container=
    for container in $containers; do
        if [[ $OPT_FORCE -eq 1 ]]; then
            cf_clear_container $container
        fi

        cf_request_check_ok $container --silent --request DELETE
    done
}


function cf_stat_thing() {
    local thing=$1

    local tmp_file=`bf_mktemp`

    # NOTE: if we used --request HEAD instead of --head, curl would
    # expect Content-Length bytes to be sent as entity body which
    # would cause a timeout since HEAD requests don't result in a body
    cf_request_check_ok "$thing" --silent --output /dev/null --head \
                        --dump-header $tmp_file

    cat $tmp_file
    rm $tmp_file
}


function cf_stat() {
    local container=$1
    shift
    local obj_names=$@

    if [[ -z $obj_names ]]; then
        # Account or Container
        cf_stat_thing "$container"
    else
        # Objects
        local obj_name=
        for obj_name in $obj_names; do
            cf_stat_thing $container/$obj_name
        done
    fi
}


function cf_object_exists() {
    local container=$1
    local obj_name=$2

    local code=$(cf_request_return_code $container/$obj_name --silent \
                                        --output /dev/null --head)

    if [[ $code -eq 204 ]]; then
        return 0
    elif [[ $code -eq 200 ]]; then
        # This appears to be a bug in CloudFiles, 200 should not be returned
        # when entity body is absent
        return 0
    elif [[ $code -eq 404 ]]; then
        return 1
    else
        bf_die "Invalid error code $code"
    fi
}


function cf_assert_objects_missing() {
    local container=$1
    shift
    local obj_names=$@

    local obj_name=
    for obj_name in $obj_names; do
        local code=$(cf_request_return_code $container/$obj_name --silent \
                                            --output /dev/null --head)

        if [[ $code -eq 200 || $code -eq 204 ]]; then
            # The fact that CloudFiles returns a 200 here even though there is
            # no entity body is a bug per the HTTP spec, should be 204
            # instead.
            bf_die "Object '$obj_name' already exists, use -f to overwrite"
        elif [[ $code -eq 404 ]]; then
            continue
        else
            bf_die "Invalid error code $code"
        fi
    done
}


function cf_save_endpoint_config() {
    cat >> $BF_ENDPOINT_CONFIG <<EOF
CF_USER=$CF_USER
CF_API_KEY=$CF_API_KEY
CF_AUTH_URL=$CF_AUTH_URL
CF_SERVICENET=$CF_SERVICENET
CF_INSECURE=$CF_INSECURE
EOF
}


function cf_load_endpoint_config_interactive() {
    local ret=1

    if [[ -n $CF_USER && -n $CF_API_KEY ]]; then
        # If CF_USER and CF_API_KEY are set then we don't need interactive
        # mode
        return $ret
    fi

    if [[ -z $CF_USER ]]; then
        ret=0
        bf_ask_required 'CF_USER' 'CloudFiles Username:'
    fi

    if [[ -z $CF_API_KEY ]]; then
        ret=0
        bf_ask_required 'CF_API_KEY' 'CloudFiles API Key:'
    fi

    if [[ -z $CF_AUTH_URL ]]; then
        ret=0
        local auth_url=$(bf_ask_with_default us \
                         'Location or Auth URL [<url>/uk/US]:')

        if [[ $auth_url == 'uk' || $auth_url == 'UK' ]]; then
            CF_AUTH_URL=$CF_DEFAULT_AUTH_URL_UK
        elif [[ $auth_url == 'us' || $auth_url == 'US' ]]; then
            CF_AUTH_URL=$CF_DEFAULT_AUTH_URL_US
        else
            CF_AUTH_URL=$auth_url
        fi
    fi

    if [[ -z $CF_SERVICENET ]]; then
        ret=0
        CF_SERVICENET=`bf_ask_yes_no n 'Use ServiceNET'`
    fi

    if [[ -z $CF_INSECURE ]]; then
        ret=0
        CF_INSECURE=`bf_ask_yes_no n 'Allow Insecure SSL'`
    fi

    return $ret
}


#############################################################################
#                                                                           #
#                                    Main                                   #
#                                                                           #
#############################################################################


while getopts 'be:fhi:o:qt:v' opt; do
    case $opt in
        b) bf_bash_completion;;
        e) OPT_ENDPOINT=$OPTARG;;
        f) OPT_FORCE=1;;
        h) bf_help;;
        i) OPT_INPUT=$OPTARG;;
        o) OPT_OUTPUT=$OPTARG;;
        q) OPT_QUIET=1;;
        t) OPT_CONTENT_TYPE=$OPTARG;;
        v) bf_version;;
        *) bf_general_usage;;
    esac
done
shift $(($OPTIND - 1))
cmd=$1
shift
case $cmd in
    cp)         cmd_cp          $@;;
    endpoint)   cmd_endpoint    $@;;
    ls)         cmd_ls          $@;;
    get)        cmd_get         $@;;
    mkdir)      cmd_mkdir       $@;;
    mv)         cmd_mv          $@;;
    put)        cmd_put         $@;;
    rm)         cmd_rm          $@;;
    rmdir)      cmd_rmdir       $@;;
    stat)       cmd_stat        $@;;
    *)      bf_general_usage;;
esac
